# Generated by Django 4.1.7 on 2023-05-10 09:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0001_initial'),
        ('customer', '0002_alter_customer_options_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=datetime.datetime(2023, 5, 10, 16, 22, 51, 718588), editable=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('sim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='sim_manager.sim', verbose_name='Sim')),
            ],
        ),
    ]
