# Generated by Django 4.1.7 on 2023-05-10 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Sim', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 17, 20, 45, 130842), editable=False),
        ),
    ]
