# Generated by Django 4.1.7 on 2023-05-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0001_initial'),
        ('customer', '0004_alter_cartitem_options_alter_cartitem_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('sim', 'customer')},
        ),
    ]
