# Generated by Django 4.1.7 on 2023-05-10 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0001_initial'),
        ('customer', '0006_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='sim_manager.sim', verbose_name='Sim'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('sim', 'customer')},
        ),
    ]
