# Generated by Django 4.1.7 on 2023-05-13 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên chủ đề')),
                ('slug', models.SlugField(unique=True, verbose_name='Đường dẫn đẹp')),
                ('desc', models.TextField(verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Chủ đề',
                'verbose_name_plural': 'Chủ đề',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('short_desc', models.CharField(max_length=500, verbose_name='Mô tả ngắn')),
                ('thumbnail', models.ImageField(upload_to='images/', verbose_name='Hình ảnh minh họa')),
                ('slug', models.SlugField(unique=True, verbose_name='Đường dẫn đẹp')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Đính kèm')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.topic', verbose_name='Chủ đề')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
            },
        ),
    ]
