# Generated by Django 4.1.7 on 2023-05-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Bài viết', 'verbose_name_plural': 'Danh sách bài viết'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Chủ đề', 'verbose_name_plural': 'Danh sách chủ đề'},
        ),
        migrations.AlterField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Ghim'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
    ]
