# Generated by Django 4.1.7 on 2023-03-07 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên nhà mạng')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, upload_to='photos/categories', verbose_name='Logo nhà mạng:')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
            ],
            options={
                'verbose_name': 'Nhà mạng',
                'verbose_name_plural': 'Danh sách nhà mạng',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nhãn')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
            ],
            options={
                'verbose_name': 'Nhãn',
                'verbose_name_plural': 'Danh sách nhãn',
            },
        ),
        migrations.CreateModel(
            name='SIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Giảm')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('image', models.ImageField(upload_to='sim_images/', verbose_name='Ảnh SIM')),
                ('is_available', models.BooleanField(default=True, verbose_name='Khả thi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sims', to='sim_manager.network', verbose_name='Nhà mạng')),
                ('tags', models.ManyToManyField(related_name='sims', to='sim_manager.tag', verbose_name='Loại SIM')),
            ],
            options={
                'verbose_name': 'SIM',
                'verbose_name_plural': 'Danh sách SIM',
            },
        ),
    ]
