# Generated by Django 4.1.7 on 2023-03-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0002_alter_sim_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá'),
        ),
    ]
