# Generated by Django 4.1.7 on 2023-03-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0003_alter_sim_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/categories', verbose_name='Logo nhà mạng:'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='description',
            field=models.TextField(null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='image',
            field=models.ImageField(null=True, upload_to='sim_images/', verbose_name='Ảnh SIM'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(null=True, verbose_name='Mô tả'),
        ),
    ]
