# Generated by Django 4.1.7 on 2023-03-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0004_alter_network_image_alter_sim_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='image',
            new_name='image_logo',
        ),
        migrations.AddField(
            model_name='network',
            name='image_card',
            field=models.ImageField(null=True, upload_to='photos/categories', verbose_name='Ảnh thẻ SIM:'),
        ),
    ]
