# Generated by Django 4.1.7 on 2023-03-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0005_rename_image_network_image_logo_network_image_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='image_card',
            new_name='image_simcard',
        ),
    ]
