# Generated by Django 4.1.7 on 2023-03-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0006_rename_image_card_network_image_simcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='image_logo',
            field=models.ImageField(null=True, upload_to='photos/networks', verbose_name='Logo nhà mạng:'),
        ),
        migrations.AlterField(
            model_name='network',
            name='image_simcard',
            field=models.ImageField(null=True, upload_to='photos/networks', verbose_name='Ảnh thẻ SIM:'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
    ]
