# Generated by Django 4.1.7 on 2023-03-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0008_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sim_images/', verbose_name='Ảnh SIM'),
        ),
    ]
