# Generated by Django 4.1.7 on 2023-05-10 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1, null=True)),
                ('cccd_image', models.ImageField(blank=True, null=True, upload_to='cccd_images/')),
                ('portrait_image', models.ImageField(blank=True, null=True, upload_to='portrait_images/')),
                ('payment_method', models.CharField(choices=[('COD', 'Trả tiền khi nhận hàng'), ('TRANSFER', 'Chuyển khoản')], max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('PENDING', 'Chuẩn bị tiếp nhận'), ('PROCESSING', 'Đang xử lý'), ('SHIPPING', 'Đang giao hàng'), ('DELIVERED', 'Đã giao hàng')], max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
        ),
    ]
