# Generated by Django 4.1.7 on 2023-05-12 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0001_initial'),
        ('order', '0004_alter_order_options_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='sim_manager.sim', verbose_name='Sim'),
        ),
    ]
