# Generated by Django 4.1.7 on 2023-05-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mã giao dịch'),
        ),
    ]
